version: '3'

services:
  cadvisor:
    image:  google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: always
    privileged: true
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    - /cgroup:/cgroup:ro

